version: '3'
services:
  redis:
    image: "redis"
    command: ["redis-server", "--appendonly", "yes"]
    container_name: redis
    volumes:
      - C:/Docker/redis/data:/var/lib/redis/data
    ports:
      - 6379:6379