version: '3'
services:
  prometheus:
    image: prom/prometheus
    container_name: "prometheus"
    volumes:
      - ./volumes/config:/prometheus/config
    command:
      - '--config.file=/prometheus/config/prometheus.yml'
    ports:
      - 9090:9090